#!/bin/sh

if pgrep parec
then 
	# Stop recording audio
	pkill parec
else
	# Output device (use "pacmd list-sinks | grep -e 'name:' -e 'index' -e 'Speakers'" command to determine)
	deviceMonitor="alsa_output.usb-Audioengine_Ltd._Audioengine_2__ABCDEFB1180003-00.analog-stereo.monitor"

	# 5-character random string
	rand=$(cat /dev/urandom | tr -dc 'A-Z0-9' | fold -w 7 | head -n 1)

	# Construct filename
	filename="${PWD}/Downloads/out_${rand}.mp3"

	# Record audio to the file
	parec -d $deviceMonitor --volume=65536 | lame -r -V7 - $filename

	# Copy the file to the clipboard
	echo "file://${filename}"|xclip -i -sel c -t text/uri-list
fi
