#!/bin/sh

if pgrep parec
then 
	# Stop recording audio
	pkill parec
else
	# Output device (the default one)
	# For more use "pacmd list-sinks | grep -e 'name:' -e 'index' -e 'Speakers'" command
	deviceMonitor="@DEFAULT_MONITOR@"


	# 5-character random string
	rand=$(cat /dev/urandom | tr -dc 'A-Z0-9' | fold -w 7 | head -n 1)

	# Construct filename
	filename="$(xdg-user-dir DOWNLOAD)/out_${rand}.mp3"

	# Record audio to the file
	parec -d $deviceMonitor --volume=65536 | lame -r -V7 - $filename

	# Copy the file to the clipboard
	echo "file://${filename}"|xclip -i -sel c -t text/uri-list
fi
